import React from "react";
import "./style.css";


function Resources() {
    return (
        <div classNameName="parentElement">
            <h1>What is CryptoCurrency?</h1>

            <p> The world of crypto-currencies is an exciting place. Less than a decade old, crypto-currencies are a revolution in both how societies think about money and how savvy investors can reap profits. But this world is not without its dangers and the un-initiated can suffer untold losses.
                        At Crypto-Currency Tracker, we don't just provide an easy means of tracking current and potential investments, we provide a range of links to informative articles that represent differing views on the market: a general overview, positive views and even more negative points of view.</p>

            {/* firs row coins */}
                <div className="container">
                    <div className="row">
                         <div className="col">

                         <button  type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal1">
                            Bitcoin</button>

                            <div className="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Bitcoin</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/L-Qhv8kLESY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            <h5>a type of digital currency in which a record of transactions is maintained and new units of currency are generated by the computational solution of mathematical problems, and which operates independently of a central bank.</h5>
                            <a href="https://en.wikipedia.org/wiki/Litecoin" target="_blank">Litecoin | From Wikipedia, the free encyclopedia</a>
                        <br/>                             <a href="https://en.wikipedia.org/wiki/Litecoin" target="_blank">Litecoin | From Wikipedia, the free encyclopedia</a>

                                    </div>
                                    </div>
                                    </div>
                                    </div>

                        </div>
                        <div className="col">
                        

                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal2">
                            Litecoin</button>

                            <div className="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Litecoin</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                            <iframe width="560" height="315" src="https://www.youtube.com/embed/q7B7S88RtV8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        <h5>Litecoin (LTC or Ł) is a peer-to-peer cryptocurrency and open-source software project released under the MIT/X11 license. Creation and transfer of coins is based on an open source cryptographic protocol and is not managed by any central authority. ... In technical details, litecoin is nearly identical to Bitcoin.</h5>
                                        <a href="https://en.wikipedia.org/wiki/Litecoin" target="_blank">Litecoin | From Wikipedia, the free encyclopedia</a>
                                        <br/><a href="https://www.investopedia.com/articles/investing/042015/bitcoin-vs-litecoin-whats-difference.asp" target="_blank">Bitcoin vs. Litecoin: What's the Difference?</a>
                                       <br/> <a href="https://www.investopedia.com/articles/investing/040515/what-litecoin-and-how-does-it-work.asp" target="_blank">What Is Litecoin, and How Does It Work?</a>
                                      <br/>  <a href="https://litecoin.org/" target="_blank">Litecoin.org</a>
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                        <div className="col">


                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal3">
                            Ethereum</button>

                            <div className="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Ethereum</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                        <div className="col">
                        

                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal4">
                        Zcash</button>

                            <div className="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Zcash</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                </div>
                </div>


{/* second row of coins */}

<div className="container">
                    <div className="row">
                         <div className="col">

                         <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal5">
                            Dash</button>

                            <div className="modal fade" id="modal5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Dash</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>

                        </div>
                        <div className="col">
                        

                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal6">
                            Ripple</button>

                            <div className="modal fade" id="modal6" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Ripple</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                        <div className="col">


                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal7">
                            Monero</button>

                            <div className="modal fade" id="modal7" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Monero</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                        <div className="col">
                        

                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal8">
                            Bitcoin Cash</button>

                            <div className="modal fade" id="modal8" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Bitcoin Cash</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                </div>
                </div>


                {/* third row of coins */}

                <div className="container">
                    <div className="row">
                         <div className="col">

                         <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal9">
                            Neo</button>

                            <div className="modal fade" id="modal9" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Neo</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        abc
                                    </div>
                                    </div>
                                    </div>
                                    </div>

                        </div>
                        <div className="col">
                        

                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal10">
                            Cardano</button>

                            <div className="modal fade" id="modal10" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">Cardano</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        xyz
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                        <div className="col">


                        <button type="button" className="btn btn-primary coinButton" data-toggle="modal" data-target="#modal11">
                            EOS</button>

                            <div className="modal fade" id="modal11" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div className="modal-dialog" role="document">
                                <div className="modal-content">

                            <div className="modal-header">
                                        <h5 className="modal-title" id="exampleModalLabel">EOS</h5>
                                        <button type="button" className="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>

                            <div className="modal-body">
                                        ...
                                    </div>
                                    </div>
                                    </div>
                                    </div>
                        </div>
                      
                </div>
                </div>









        </div>






  
  
    );
}

export default Resources;